version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jeecorso
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - my_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  my_data:
